<?php
/**
 * 2007-2020 PrestaShop
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@prestashop.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
 * versions in the future. If you wish to customize PrestaShop for your
 * needs please refer to http://www.prestashop.com for more information.
 *
 *  @author    PrestaShop SA <contact@prestashop.com>
 *  @copyright 2007-2020 PrestaShop SA
 *  @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 *  International Registered Trademark & Property of PrestaShop SA
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

class Fozzy_promotions extends Module {

    function __construct()
    {
        $this->name = 'fozzy_promotions';
        $this->tab = 'administration';
        $this->version = '1.0.0';
        $this->author = 'Rudyk M.';
        $this->need_instance = 1;

        /**
         * Set $this->bootstrap to true if your module is compliant with bootstrap (PrestaShop 1.6)
         */
        $this->bootstrap = true;

        parent::__construct();

        $this->displayName = $this->l('Modul promotions');
        $this->description = $this->l('Promotions for Fozzy');

        $this->ps_versions_compliancy = array('min' => '1.7', 'max' => _PS_VERSION_);
    }

    /**
     * Установка модуля.
     * Module installation.
     * @return bool
     */
    public function install() {
        include dirname(__FILE__) . '/sql/install.php';
        $this->installTab();
        return parent::install(); // TODO: Change the autogenerated stub
    }

    /**
     * Добавление ссылки на модуль в главное меню.
     * Adding a link to the module to the main menu.
     * @return bool
     */
    public function installTab() {
        $id = Tab::getIdFromClassName('AdminCatalog');
        $tab = new Tab();
        $tab->class_name = 'AdminPromotions';
        $tab->name[(int) (Configuration::get('PS_LANG_DEFAULT'))] = $this->l('Modul promotions');
        $tab->id_parent = $id;
        $tab->module = $this->name;
        $tab->add();
        return true;
    }

    /**
     * Удаление модуля.
     * Removing a module.
     * @return bool
     */
    public function uninstall() {

        $idTabs = array();
        $idTabs[] = Tab::getIdFromClassName('AdminPromotions');
        foreach ($idTabs as $idTab) {
            if ($idTab) {
                $tab = new Tab($idTab);
                $tab->delete();
            }
        }

        include dirname(__FILE__) . '/sql/uninstall.php';
        return parent::uninstall(); // TODO: Change the autogenerated stub
    }


    /**
     * Основная функция модуля.
     * The main function of the module.
     * @return string
     */
    public function getContent() {

    }
}